/*
 * NocSif menu icon font — codepoint macros (UI-shell P3.2). GENERATED by gen_icons.py.
 *
 * One 4bpp LVGL bitmap font (nocsif_icons) whose glyphs are the mockup's line icons,
 * stroke-expanded to filled outlines. Use a glyph as the text of a label styled with
 * &nocsif_icons and recolour it with the normal text colour (steel at rest -> accent on
 * press). Codepoints are Private-Use U+E000+; these UTF-8 macros hide the raw value.
 */
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_font_t nocsif_icons;
extern const lv_font_t nocsif_icons_lg;   /* P8 v2.2: large celestial motifs (Home hub) */
extern const lv_font_t nocsif_icons_cc;   /* P8 v2.4: 48px Control-Center toggles, lighter stroke */
extern const lv_font_t nocsif_icons_xl;   /* P8 v2.8: full set, large + thin (floating planets, icon picker) */

#define NOCSIF_ICON_WIFI     "\xEE\x80\x80"   /* U+E000 */
#define NOCSIF_ICON_NFC      "\xEE\x80\x81"   /* U+E001 */
#define NOCSIF_ICON_USB      "\xEE\x80\x82"   /* U+E002 */
#define NOCSIF_ICON_BLE      "\xEE\x80\x83"   /* U+E003 */
#define NOCSIF_ICON_SYS      "\xEE\x80\x84"   /* U+E004 */
#define NOCSIF_ICON_BELL     "\xEE\x80\x85"   /* U+E005 */
#define NOCSIF_ICON_FLASH    "\xEE\x80\x86"   /* U+E006 */
#define NOCSIF_ICON_HUNT     "\xEE\x80\x87"   /* U+E007 */
#define NOCSIF_ICON_MON      "\xEE\x80\x88"   /* U+E008 */
#define NOCSIF_ICON_AP       "\xEE\x80\x89"   /* U+E009 */
#define NOCSIF_ICON_LOCK     "\xEE\x80\x8A"   /* U+E00A */
#define NOCSIF_ICON_DRIVE    "\xEE\x80\x8B"   /* U+E00B */
#define NOCSIF_ICON_CHEV     "\xEE\x80\x8C"   /* U+E00C */
#define NOCSIF_ICON_BACK     "\xEE\x80\x8D"   /* U+E00D */
#define NOCSIF_ICON_UP       "\xEE\x80\x8E"   /* U+E00E */
#define NOCSIF_ICON_DOWN     "\xEE\x80\x8F"   /* U+E00F */
#define NOCSIF_ICON_STAR     "\xEE\x80\x90"   /* U+E010 */
#define NOCSIF_ICON_RADIO    "\xEE\x80\x91"   /* U+E011 */
#define NOCSIF_ICON_LOC      "\xEE\x80\x92"   /* U+E012 */
#define NOCSIF_ICON_CLOCK    "\xEE\x80\x93"   /* U+E013 */
#define NOCSIF_ICON_MIC      "\xEE\x80\x94"   /* U+E014 */
#define NOCSIF_ICON_ACT      "\xEE\x80\x95"   /* U+E015 */
#define NOCSIF_ICON_NAV      "\xEE\x80\x96"   /* U+E016 */
#define NOCSIF_ICON_WX       "\xEE\x80\x97"   /* U+E017 */
#define NOCSIF_ICON_SUN      "\xEE\x80\x98"   /* U+E018 */
#define NOCSIF_ICON_RAIN     "\xEE\x80\x99"   /* U+E019 */
#define NOCSIF_ICON_NOTE     "\xEE\x80\x9A"   /* U+E01A */
#define NOCSIF_ICON_FOLDER   "\xEE\x80\x9B"   /* U+E01B */
#define NOCSIF_ICON_AUTO     "\xEE\x80\x9C"   /* U+E01C */
#define NOCSIF_ICON_THEME    "\xEE\x80\x9D"   /* U+E01D */
#define NOCSIF_ICON_BATT     "\xEE\x80\x9E"   /* U+E01E */
#define NOCSIF_ICON_REFRESH  "\xEE\x80\x9F"   /* U+E01F */
#define NOCSIF_ICON_GLOBE    "\xEE\x80\xA0"   /* U+E020 */
#define NOCSIF_ICON_PLAY     "\xEE\x80\xA1"   /* U+E021 */
#define NOCSIF_ICON_PHONE    "\xEE\x80\xA2"   /* U+E022 */
#define NOCSIF_ICON_KEY      "\xEE\x80\xA3"   /* U+E023 */
#define NOCSIF_ICON_MSG      "\xEE\x80\xA4"   /* U+E024 */
#define NOCSIF_ICON_CAST     "\xEE\x80\xA5"   /* U+E025 */
#define NOCSIF_ICON_MOON     "\xEE\x80\xA6"   /* U+E026 */
#define NOCSIF_ICON_PLANET   "\xEE\x80\xA7"   /* U+E027 */
#define NOCSIF_ICON_PLANE    "\xEE\x80\xA8"   /* U+E028 */
#define NOCSIF_ICON_PREV     "\xEE\x80\xA9"   /* U+E029 */
#define NOCSIF_ICON_NEXT     "\xEE\x80\xAA"   /* U+E02A */
#define NOCSIF_ICON_SPEAKER  "\xEE\x80\xAB"   /* U+E02B */
#define NOCSIF_ICON_PAUSE    "\xEE\x80\xAC"   /* U+E02C */
#define NOCSIF_ICON_SNOW     "\xEE\x80\xAD"   /* U+E02D */
#define NOCSIF_ICON_STORM    "\xEE\x80\xAE"   /* U+E02E */
#define NOCSIF_ICON_FOG      "\xEE\x80\xAF"   /* U+E02F */

#ifdef __cplusplus
}
#endif
