#!/usr/bin/env python3
"""
Rasterize the mockup's #i-star engraved 4-point celestial star (docs/design/ui-mockup.html
line 128) into an A8 (alpha-only) LVGL v9.3 image descriptor.

The SVG is fill="none" stroke="currentColor" stroke-width="0.9" in a 24x24 viewBox: a closed
outline traced through 4 tips + 4 concave inner points via 8 cubic Beziers. We evaluate the
Beziers directly (no SVG lib), stroke the polyline at high supersample with Pillow, then
box-downsample to an A8 master. The alpha channel IS the engraving; the firmware recolors it
(gray / violet) per placement via lv_draw_image recolor. Reusable by boot (P5) + About.
"""
import math
from PIL import Image, ImageDraw

# ---- path: 8 cubic segments in the 24x24 viewBox (P0 then (C1,C2,E) x8) ---------
P0 = (12.0, 2.4)
SEGS = [
    ((12.5, 7.5),  (12.7, 9.3),  (15.2, 10.8)),
    ((16.7, 11.7), (18.5, 11.9), (21.6, 12.0)),
    ((18.5, 12.1), (16.7, 12.3), (15.2, 13.2)),
    ((12.7, 14.7), (12.5, 16.5), (12.0, 21.6)),
    ((11.5, 16.5), (11.3, 14.7), (8.8, 13.2)),
    ((7.3, 12.3),  (5.5, 12.1),  (2.4, 12.0)),
    ((5.5, 11.9),  (7.3, 11.7),  (8.8, 10.8)),
    ((11.3, 9.3),  (11.5, 7.5),  (12.0, 2.4)),
]
VIEWBOX = 24.0
STROKE_VB = 0.9          # stroke-width in viewBox units
MASTER = 64              # A8 master size (px); downscaled in-firmware per placement
SS = 8                   # supersample factor
SYM = "nocsif_img_star"


def cubic(p0, c1, c2, p3, n=48):
    out = []
    for i in range(n + 1):
        t = i / n
        u = 1 - t
        x = u*u*u*p0[0] + 3*u*u*t*c1[0] + 3*u*t*t*c2[0] + t*t*t*p3[0]
        y = u*u*u*p0[1] + 3*u*u*t*c1[1] + 3*u*t*t*c2[1] + t*t*t*p3[1]
        out.append((x, y))
    return out


def build_polyline():
    pts = []
    cur = P0
    for (c1, c2, e) in SEGS:
        seg = cubic(cur, c1, c2, e)
        pts.extend(seg if not pts else seg[1:])   # avoid duplicate join points
        cur = e
    return pts


def main():
    big = MASTER * SS
    scale = big / VIEWBOX
    stroke_px = max(1, round(STROKE_VB * scale))

    img = Image.new("L", (big, big), 0)      # alpha-only, transparent ground
    dr = ImageDraw.Draw(img)
    poly = [(x * scale, y * scale) for (x, y) in build_polyline()]
    # stroke the closed outline; round joins so the concave tips stay clean
    dr.line(poly, fill=255, width=stroke_px, joint="curve")
    # round the caps/joins Pillow's 'curve' can miss: dab a disc at each vertex
    r = stroke_px / 2.0
    for (x, y) in poly:
        dr.ellipse([x - r, y - r, x + r, y + r], fill=255)

    a8 = img.resize((MASTER, MASTER), Image.LANCZOS)   # box/lanczos downsample = AA
    data = a8.tobytes()                                # row-major, 1 byte/px
    assert len(data) == MASTER * MASTER

    # save a PNG preview for eyeballing
    a8.save("star_preview.png")

    # coverage sanity
    nz = sum(1 for b in data if b)
    peak = max(data)
    print(f"master={MASTER} stroke_px={stroke_px} nonzero={nz}/{len(data)} peak={peak}")

    emit_c(data)


def emit_c(data):
    w = h = MASTER
    lines = []
    lines.append('/*')
    lines.append(' * NocSif -- engraved 4-point celestial star, A8 (alpha-only) LVGL image (UI-shell P2).')
    lines.append(' *')
    lines.append(' * GENERATED by gen_star.py (this dir) from the docs/design/ui-mockup.html #i-star path')
    lines.append(' * (8 cubic Beziers, 24x24 viewBox, 0.9 stroke). A8 so the firmware recolors it gray or')
    lines.append(' * violet per placement (lv_draw_image recolor). Master is %dx%d; downscaled in-firmware.' % (w, h))
    lines.append(' * The #include block is a plain "lvgl.h" (matches ui.c; managed-component path guard).')
    lines.append(' */')
    lines.append('#include "lvgl.h"')
    lines.append('')
    lines.append('#ifndef LV_ATTRIBUTE_MEM_ALIGN')
    lines.append('#define LV_ATTRIBUTE_MEM_ALIGN')
    lines.append('#endif')
    lines.append('')
    lines.append('static const LV_ATTRIBUTE_MEM_ALIGN uint8_t %s_map[] = {' % SYM)
    # hex bytes, 16 per line
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        lines.append('    ' + ''.join('0x%02x,' % b for b in chunk))
    lines.append('};')
    lines.append('')
    lines.append('const lv_image_dsc_t %s = {' % SYM)
    lines.append('    .header = {')
    lines.append('        .magic = LV_IMAGE_HEADER_MAGIC,')
    lines.append('        .cf = LV_COLOR_FORMAT_A8,')
    lines.append('        .flags = 0,')
    lines.append('        .w = %d,' % w)
    lines.append('        .h = %d,' % h)
    lines.append('        .stride = %d,' % w)   # A8 = 1 byte/px
    lines.append('        .reserved_2 = 0,')
    lines.append('    },')
    lines.append('    .data_size = %d,' % (w * h))
    lines.append('    .data = %s_map,' % SYM)
    lines.append('};')
    lines.append('')
    open("nocsif_img_star.c", "w", newline="\n", encoding="utf-8").write("\n".join(lines) + "\n")
    print("wrote nocsif_img_star.c (%d data bytes)" % len(data))


if __name__ == "__main__":
    main()
